services:
  - type: web
    name: autoeda-agent
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        fromDatabase: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
    autoDeploy: true

